"""
src/models/asset.py

Asset domain model.

Represents any digital asset used or generated within
Mahy Mythic Labs Studio OS.

Examples
--------
• AI Images
• AI Videos
• Narration Audio
• Background Music
• Sound Effects
• Research PDFs
• Subtitle Files
• Thumbnail Images

Relationships
-------------
Project
    └── Episode
            └── Scene
                    └── Shot
                            └── Generation
                                    └── Asset

Python
------
>=3.11

Pydantic
---------
>=2.x
"""

from __future__ import annotations

from datetime import UTC, datetime
from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import Field, field_validator

from .base import EntityModel

# ==============================================================================
# Enumerations
# ==============================================================================


class AssetType(str, Enum):
    """
    Supported asset types.
    """

    IMAGE = "image"

    VIDEO = "video"

    AUDIO = "audio"

    MUSIC = "music"

    VOICE = "voice"

    SCRIPT = "script"

    SUBTITLE = "subtitle"

    DOCUMENT = "document"

    PDF = "pdf"

    MODEL = "model"

    ARCHIVE = "archive"

    OTHER = "other"


class AssetStatus(str, Enum):
    """
    Asset lifecycle.
    """

    CREATED = "created"

    IMPORTED = "imported"

    GENERATED = "generated"

    PROCESSING = "processing"

    READY = "ready"

    ARCHIVED = "archived"

    DELETED = "deleted"


class StorageProvider(str, Enum):
    """
    Storage backend.
    """

    LOCAL = "local"

    S3 = "s3"

    GCS = "gcs"

    AZURE = "azure"

    FABRIC = "fabric"

    OTHER = "other"


# ==============================================================================
# Asset Entity
# ==============================================================================


class Asset(EntityModel):
    """
    Represents a digital asset managed by Studio OS.

    Assets may be generated by AI providers or imported from external
    sources. They represent the final media used throughout the
    production pipeline.
    """

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------

    project_id: UUID | None = Field(
        default=None,
        description="Associated project.",
    )

    episode_id: UUID | None = Field(
        default=None,
        description="Associated episode.",
    )

    scene_id: UUID | None = Field(
        default=None,
        description="Associated scene.",
    )

    shot_id: UUID | None = Field(
        default=None,
        description="Associated shot.",
    )

    generation_id: UUID | None = Field(
        default=None,
        description="Source generation.",
    )

    # ------------------------------------------------------------------
    # Classification
    # ------------------------------------------------------------------

    asset_type: AssetType = Field(
        description="Type of asset.",
    )

    status: AssetStatus = Field(
        default=AssetStatus.CREATED,
        description="Lifecycle status.",
    )

    name: str = Field(
        min_length=1,
        max_length=200,
        description="Human readable asset name.",
    )

    description: str | None = Field(
        default=None,
        description="Optional description.",
    )

    tags: list[str] = Field(
        default_factory=list,
        description="Search tags.",
    )

    # ------------------------------------------------------------------
    # File Information
    # ------------------------------------------------------------------

    filename: str = Field(
        min_length=1,
        description="Filename including extension.",
    )

    extension: str = Field(
        min_length=1,
        description="File extension.",
    )

    mime_type: str = Field(
        min_length=1,
        description="MIME type.",
    )

    checksum: str | None = Field(
        default=None,
        description="SHA256 or similar checksum.",
    )

    file_size_bytes: int = Field(
        default=0,
        ge=0,
        description="File size.",
    )

    # ------------------------------------------------------------------
    # Storage
    # ------------------------------------------------------------------

    storage_provider: StorageProvider = Field(
        default=StorageProvider.LOCAL,
    )

    bucket_name: str | None = Field(
        default=None,
    )

    storage_uri: str | None = Field(
        default=None,
        description="Cloud storage URI.",
    )

    local_path: str | None = Field(
        default=None,
        description="Local filesystem path.",
    )

    thumbnail_uri: str | None = Field(
        default=None,
    )

    preview_uri: str | None = Field(
        default=None,
    )

    # ------------------------------------------------------------------
    # Technical Metadata
    # ------------------------------------------------------------------

    width: int | None = Field(
        default=None,
        ge=1,
    )

    height: int | None = Field(
        default=None,
        ge=1,
    )

    duration_seconds: float | None = Field(
        default=None,
        ge=0,
    )

    fps: float | None = Field(
        default=None,
        ge=0,
    )

    bitrate: int | None = Field(
        default=None,
        ge=0,
    )

    sample_rate: int | None = Field(
        default=None,
        ge=0,
    )

    channels: int | None = Field(
        default=None,
        ge=1,
    )

    codec: str | None = Field(
        default=None,
    )

    language: str | None = Field(
        default=None,
    )

    # ------------------------------------------------------------------
    # Ownership
    # ------------------------------------------------------------------

    creator: str | None = Field(
        default=None,
        description="Creator or author.",
    )

    copyright: str | None = Field(
        default=None,
    )

    license: str | None = Field(
        default=None,
    )

    source: str | None = Field(
        default=None,
        description="Original source.",
    )

    # ------------------------------------------------------------------
    # Metadata
    # ------------------------------------------------------------------

    metadata: dict[str, Any] = Field(
        default_factory=dict,
    )

    # ------------------------------------------------------------------
    # Validators
    # ------------------------------------------------------------------

    @field_validator("name")
    @classmethod
    def validate_name(cls, value: str) -> str:
        value = value.strip()

        if not value:
            raise ValueError(
                "Asset name cannot be empty."
            )

        return value

    @field_validator("filename")
    @classmethod
    def validate_filename(cls, value: str) -> str:
        value = value.strip()

        if not value:
            raise ValueError(
                "Filename cannot be empty."
            )

        return value

    @field_validator("extension")
    @classmethod
    def validate_extension(cls, value: str) -> str:
        value = value.strip().lower()

        if value.startswith("."):
            value = value[1:]

        if not value:
            raise ValueError(
                "Invalid file extension."
            )

        return value

    @field_validator("mime_type")
    @classmethod
    def validate_mime_type(cls, value: str) -> str:
        value = value.strip()

        if "/" not in value:
            raise ValueError(
                "Invalid MIME type."
            )

        return value

    # ------------------------------------------------------------------
    # Business Validation
    # ------------------------------------------------------------------

    def validate_state(self) -> None:
        """
        Validate asset consistency.
        """

        if (
            self.width is not None
            and self.height is None
        ):
            raise ValueError(
                "Height is required when width is specified."
            )

        if (
            self.height is not None
            and self.width is None
        ):
            raise ValueError(
                "Width is required when height is specified."
            )

        if (
            self.file_size_bytes < 0
        ):
            raise ValueError(
                "Invalid file size."
            )

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    def mark_generated(self) -> None:
        """
        Asset successfully generated.
        """

        self.status = AssetStatus.GENERATED
        self.touch()

    def mark_processing(self) -> None:
        """
        Asset is being processed.
        """

        self.status = AssetStatus.PROCESSING
        self.touch()

    def mark_ready(self) -> None:
        """
        Asset ready for use.
        """

        self.status = AssetStatus.READY
        self.validate_state()
        self.touch()

    def archive(self) -> None:
        """
        Archive asset.
        """

        self.status = AssetStatus.ARCHIVED
        self.touch()

    def delete(self) -> None:
        """
        Mark asset as deleted.
        """

        self.status = AssetStatus.DELETED
        self.touch()

    # ------------------------------------------------------------------
    # Storage Helpers
    # ------------------------------------------------------------------

    def set_local_path(
        self,
        path: str,
    ) -> None:
        """
        Update local filesystem path.
        """

        self.local_path = path
        self.touch()

    def set_storage_uri(
        self,
        uri: str,
    ) -> None:
        """
        Update cloud storage URI.
        """

        self.storage_uri = uri
        self.touch()

    def set_thumbnail(
        self,
        uri: str,
    ) -> None:
        """
        Set thumbnail URI.
        """

        self.thumbnail_uri = uri
        self.touch()

    def set_preview(
        self,
        uri: str,
    ) -> None:
        """
        Set preview URI.
        """

        self.preview_uri = uri
        self.touch()

    # ------------------------------------------------------------------
    # Metadata Helpers
    # ------------------------------------------------------------------

    def add_tag(
        self,
        tag: str,
    ) -> None:
        """
        Add a tag.
        """

        tag = tag.strip()

        if tag and tag not in self.tags:
            self.tags.append(tag)
            self.touch()

    def remove_tag(
        self,
        tag: str,
    ) -> None:
        """
        Remove a tag.
        """

        if tag in self.tags:
            self.tags.remove(tag)
            self.touch()

    def update_metadata(
        self,
        key: str,
        value: Any,
    ) -> None:
        """
        Update metadata.
        """

        self.metadata[key] = value
        self.touch()

    def remove_metadata(
        self,
        key: str,
    ) -> None:
        """
        Remove metadata entry.
        """

        self.metadata.pop(key, None)
        self.touch()

    # ------------------------------------------------------------------
    # Convenience Properties
    # ------------------------------------------------------------------

    @property
    def is_image(self) -> bool:
        """
        True if this asset is an image.
        """
        return self.asset_type == AssetType.IMAGE

    @property
    def is_video(self) -> bool:
        """
        True if this asset is a video.
        """
        return self.asset_type == AssetType.VIDEO

    @property
    def is_audio(self) -> bool:
        """
        True if this asset is an audio asset.
        """
        return self.asset_type in {
            AssetType.AUDIO,
            AssetType.MUSIC,
            AssetType.VOICE,
        }

    @property
    def is_document(self) -> bool:
        """
        True if this asset is a document.
        """
        return self.asset_type in {
            AssetType.DOCUMENT,
            AssetType.PDF,
            AssetType.SCRIPT,
            AssetType.SUBTITLE,
        }

    @property
    def is_ready(self) -> bool:
        """
        Returns True if asset is ready for use.
        """
        return self.status == AssetStatus.READY

    @property
    def is_deleted(self) -> bool:
        """
        Returns True if asset is deleted.
        """
        return self.status == AssetStatus.DELETED

    @property
    def has_thumbnail(self) -> bool:
        """
        Returns True if thumbnail exists.
        """
        return bool(self.thumbnail_uri)

    @property
    def has_preview(self) -> bool:
        """
        Returns True if preview exists.
        """
        return bool(self.preview_uri)

    @property
    def is_stored_locally(self) -> bool:
        """
        Returns True if stored on local filesystem.
        """
        return self.local_path is not None

    @property
    def is_cloud_asset(self) -> bool:
        """
        Returns True if uploaded to cloud storage.
        """
        return self.storage_uri is not None

    @property
    def resolution(self) -> str | None:
        """
        Returns resolution as WIDTHxHEIGHT.
        """

        if self.width is None or self.height is None:
            return None

        return f"{self.width}x{self.height}"

    @property
    def aspect_ratio(self) -> float | None:
        """
        Returns aspect ratio.
        """

        if (
            self.width is None
            or self.height is None
            or self.height == 0
        ):
            return None

        return round(
            self.width / self.height,
            3,
        )

    @property
    def size_mb(self) -> float:
        """
        File size in megabytes.
        """
        return round(
            self.file_size_bytes / (1024 * 1024),
            2,
        )

    @property
    def display_name(self) -> str:
        """
        Display-friendly asset name.
        """

        if self.description:
            return f"{self.name} ({self.description})"

        return self.name

    # ------------------------------------------------------------------
    # Utility Methods
    # ------------------------------------------------------------------

    def rename(
        self,
        new_name: str,
    ) -> None:
        """
        Rename asset.
        """

        self.name = new_name.strip()
        self.touch()

    def update_file(
        self,
        *,
        filename: str | None = None,
        extension: str | None = None,
        mime_type: str | None = None,
    ) -> None:
        """
        Update file information.
        """

        if filename is not None:
            self.filename = filename

        if extension is not None:
            self.extension = extension

        if mime_type is not None:
            self.mime_type = mime_type

        self.touch()

    def clone_metadata(self) -> dict[str, Any]:
        """
        Return a deep copy of metadata.
        """
        return dict(self.metadata)

    # ------------------------------------------------------------------
    # Representation
    # ------------------------------------------------------------------

    def __str__(self) -> str:
        return (
            f"{self.asset_type.value}: "
            f"{self.name}"
        )

    def __repr__(self) -> str:
        return (
            "Asset("
            f"id={self.id}, "
            f"name={self.name!r}, "
            f"type={self.asset_type.value!r}, "
            f"status={self.status.value!r}"
            ")"
        )